const REQUEST_MOVIES = 'REQUEST_MOVIES'
const FILTER_MOVIES = 'FILTER_MOVIES' 
const IS_FILTERING= 'IS_FILTERING'
const STORE_LOGGED_USER = 'STORE_LOGGED_USER'

export { REQUEST_MOVIES , FILTER_MOVIES , IS_FILTERING , STORE_LOGGED_USER }