const REQUEST_MOVIES = 'REQUEST_MOVIES'
const FILTER_MOVIES = 'FILTER_MOVIES' 
const IS_FILTERING= 'IS_FILTERING'
const STORE_LOGGED_USER = 'STORE_LOGGED_USER'
const UPDATE_AUTH_OBJECT = 'UPDATE_AUTH_OBJECT'
const LOAD_MESSAGE = 'LOAD_MESSAGE'
const UPDATE_PAGE = 'UPDATE_PAGE'
const FLUSH_AUTH = 'FLUSH_AUTH' 

export { REQUEST_MOVIES , FILTER_MOVIES , IS_FILTERING , STORE_LOGGED_USER , UPDATE_AUTH_OBJECT , LOAD_MESSAGE , UPDATE_PAGE , FLUSH_AUTH }